# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
    themes: !include_dir_merge_named themes

automation: !include_dir_merge_list automations/
script: !include scripts.yaml
scene: !include scenes.yaml
template: !include_dir_merge_list templates/

#cloudflared tunnel
http:
    use_x_forwarded_for: true
    trusted_proxies:
        - 172.30.33.0/24

# Packages
homeassistant:
    packages:
        # Solar Analytics
        pack_1: !include solar_analytics/solar_analytics_3phase.yaml

# Custom Controls
lovelace:
    resources:
        - url: /local/custom_cards/solar_control/solar-control-card.js?v=1.1
          type: module
